/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedShellRouteImport } from './routes/_authed/_shell'
import { Route as AuthedChangePasswordRouteImport } from './routes/_authed/change-password'
import { Route as AuthedShellIndexRouteImport } from './routes/_authed/_shell/index'
import { Route as AuthedShellOrdersIndexRouteImport } from './routes/_authed/_shell/orders/index'
import { Route as AuthedShellOrdersOrderIdRouteImport } from './routes/_authed/_shell/orders/$orderId'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedShellRoute = AuthedShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedChangePasswordRoute = AuthedChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedShellIndexRoute = AuthedShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedShellRoute,
} as any)
const AuthedShellOrdersIndexRoute = AuthedShellOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AuthedShellRoute,
} as any)
const AuthedShellOrdersOrderIdRoute =
  AuthedShellOrdersOrderIdRouteImport.update({
    id: '/orders/$orderId',
    path: '/orders/$orderId',
    getParentRoute: () => AuthedShellRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedShellIndexRoute
  '/login': typeof LoginRoute
  '/change-password': typeof AuthedChangePasswordRoute
  '/orders/$orderId': typeof AuthedShellOrdersOrderIdRoute
  '/orders/': typeof AuthedShellOrdersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthedShellIndexRoute
  '/login': typeof LoginRoute
  '/change-password': typeof AuthedChangePasswordRoute
  '/orders/$orderId': typeof AuthedShellOrdersOrderIdRoute
  '/orders': typeof AuthedShellOrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/_shell': typeof AuthedShellRouteWithChildren
  '/_authed/change-password': typeof AuthedChangePasswordRoute
  '/_authed/_shell/': typeof AuthedShellIndexRoute
  '/_authed/_shell/orders/$orderId': typeof AuthedShellOrdersOrderIdRoute
  '/_authed/_shell/orders/': typeof AuthedShellOrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/login' | '/change-password' | '/orders/$orderId' | '/orders/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/change-password' | '/orders/$orderId' | '/orders'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/_authed/_shell'
    | '/_authed/change-password'
    | '/_authed/_shell/'
    | '/_authed/_shell/orders/$orderId'
    | '/_authed/_shell/orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/_shell': {
      id: '/_authed/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedShellRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/change-password': {
      id: '/_authed/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof AuthedChangePasswordRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/_shell/': {
      id: '/_authed/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedShellIndexRouteImport
      parentRoute: typeof AuthedShellRoute
    }
    '/_authed/_shell/orders/': {
      id: '/_authed/_shell/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof AuthedShellOrdersIndexRouteImport
      parentRoute: typeof AuthedShellRoute
    }
    '/_authed/_shell/orders/$orderId': {
      id: '/_authed/_shell/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof AuthedShellOrdersOrderIdRouteImport
      parentRoute: typeof AuthedShellRoute
    }
  }
}

interface AuthedShellRouteChildren {
  AuthedShellIndexRoute: typeof AuthedShellIndexRoute
  AuthedShellOrdersOrderIdRoute: typeof AuthedShellOrdersOrderIdRoute
  AuthedShellOrdersIndexRoute: typeof AuthedShellOrdersIndexRoute
}

const AuthedShellRouteChildren: AuthedShellRouteChildren = {
  AuthedShellIndexRoute: AuthedShellIndexRoute,
  AuthedShellOrdersOrderIdRoute: AuthedShellOrdersOrderIdRoute,
  AuthedShellOrdersIndexRoute: AuthedShellOrdersIndexRoute,
}

const AuthedShellRouteWithChildren = AuthedShellRoute._addFileChildren(
  AuthedShellRouteChildren,
)

interface AuthedRouteChildren {
  AuthedShellRoute: typeof AuthedShellRouteWithChildren
  AuthedChangePasswordRoute: typeof AuthedChangePasswordRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedShellRoute: AuthedShellRouteWithChildren,
  AuthedChangePasswordRoute: AuthedChangePasswordRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
